### PR TITLE
Changes made and image removed

### PR DESCRIPTION
**Pull request by akshit5565**

### CODE REVIEW

**Comment by zabihhaqqani** [comment]
@akshit5565  you have created a new branch that's great but there is no HTML or CSS file.

**Review by zabihhaqqani — CHANGES_REQUESTED** [review]
There is no HTML and CSS file.

It shows in the commit the you have deleted it.

**Comment by akshit5565** [comment]
> There is no HTML and CSS file.
> 
> It shows in the commit the you have deleted it.

I am really sorry sir, i will make another PR regarding the same.

**Comment by akshit5565** [comment]
@zabihhaqqani I have made another PR , please check and give me the hacktoberfest accepted label.

**Comment by zabihhaqqani** [comment]
sure no problem!

**Pull request closed without merging**
