### PR TITLE
footer-updated

### PR DESCRIPTION
**Pull request by Swati002**
Changes are done int footer-branch.
Is it correct now?

### CODE REVIEW

**Comment by zabihhaqqani** [comment]
sorry, @Swati002 but again you have added the entire code instead of just the changes you have made.

1. Did you fork and clone the project using git?

**Comment by Swati002** [comment]
Yes, I did fork and clone it right and followed your documentation only. 
I have not changed the entire codebase, just updated few things

**Comment by Swati002** [comment]
https://deploy-preview-27--minion-bananatranslator.netlify.app/

This is how deployed Website looks like, only the footer is changed, rest all the elements are same

**Comment by Swati002** [comment]
Will this PR be able to merge?

**Comment by zabihhaqqani** [comment]
@Swati002 the script file seems to be missing.

**Comment by zabihhaqqani** [comment]
@Swati002 It shows that you have made +225 additions and -222 deletions.

My suggestion would be to start again.

follow this step by step: https://zabihhaqqani.hashnode.dev/first-pull-request

If you face the same issue again I will try to help you out.

**Pull request closed without merging**
