### PR TITLE
Dark mode feature

### LINKED ISSUE #16: Want to add a button to switch between light and dark mode.

### PR DESCRIPTION
**Pull request by RhyshaKachari**
Fixed #16 
I have added a toggle button to switch between the dark mode and light mode. Kindly review this :)
Images:-
Light mode:
light mode

Dark mode:
dark mode

### CODE REVIEW

**Review by zabihhaqqani — CHANGES_REQUESTED** [review]
great work @RhyshaKachari 

few changes

- background-color could be dark like black
- input element white 

something like this ↓

chh

make the commits in the same PR

**Comment by zabihhaqqani** [comment]
recently there was a pull request merged so pull the changes to your local machine.

**Comment by RhyshaKachari** [comment]
@zabihhaqqani I have done the required changes. Kindly have a look.

**Comment by zabihhaqqani** [comment]
**Awesome work** @RhyshaKachari 

**Thanks for contributing.**

**Pull request merged**
